# Argo CD infra namespace — lab only.
# @see https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/
# @see https://docs.openshift.com/container_platform/latest/security/pod-security-admission.html
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
