global:
  imagePullSecrets: []
  deploymentEnvironment: production

hatchet:
  enabled: false
  waitInitImage: busybox:1.37.0

hatchet-stack:
  caddy:
    enabled: false
  api:
    fullnameOverride: repody-hatchet-api
    replicaCount: 1
    ingress:
      enabled: false
    quickstartJob:
      enabled: true
    workerTokenJob:
      enabled: true
  engine:
    fullnameOverride: repody-hatchet-engine
    replicaCount: 1
    ingress:
      enabled: false
  frontend:
    fullnameOverride: repody-hatchet-frontend
    ingress:
      enabled: false
  postgres:
    enabled: true
    primary:
      extendedConfiguration: |
        timezone = 'UTC'
  rabbitmq:
    enabled: true
