apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: repody-postgres-daily
  namespace: repody-data
  labels:
    app.kubernetes.io/part-of: repody
    app.kubernetes.io/component: postgres-backup
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: repody-postgres

