apiVersion: v1
kind: Secret
metadata:
  name: repody-postgres-app
  namespace: repody-data
type: kubernetes.io/basic-auth
stringData:
  username: audit
  password: CHANGE_ME_LONG_RANDOM_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: repody-postgres-backup
  namespace: repody-data
type: Opaque
stringData:
  ACCESS_KEY_ID: CHANGE_ME_BACKUP_ACCESS_KEY
  SECRET_ACCESS_KEY: CHANGE_ME_BACKUP_SECRET_KEY

