{{- if .Values.workerOcr.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "repody.fullname" . }}-worker-ocr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "repody.fullname" . }}-worker-ocr
  minReplicas: {{ .Values.workerOcr.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workerOcr.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workerOcr.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.workerFast.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "repody.fullname" . }}-worker-fast
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "repody.fullname" . }}-worker-fast
  minReplicas: {{ .Values.workerFast.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workerFast.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workerFast.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
