"""initial_schema

Revision ID: 9b24af3aa3c5
Revises: 
Create Date: 2026-05-19 11:53:00.075595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b24af3aa3c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_workflow_id'), 'documents', ['workflow_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('overall_status', sa.String(length=16), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary_total', sa.Integer(), nullable=False),
    sa.Column('summary_passed', sa.Integer(), nullable=False),
    sa.Column('summary_failed', sa.Integer(), nullable=False),
    sa.Column('fields_extracted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_workflow_id'), 'runs', ['workflow_id'], unique=False)
    op.create_table('workflow_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('condition_junction', sa.String(length=8), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_rules_workflow_id'), 'workflow_rules', ['workflow_id'], unique=False)
    op.create_table('rule_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('affected_fields', sa.JSON(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_results_run_id'), 'rule_results', ['run_id'], unique=False)
    op.create_table('run_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_documents_run_id'), 'run_documents', ['run_id'], unique=False)
    op.create_table('schema_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_fields_document_id'), 'schema_fields', ['document_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_document_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_document_id'], ['run_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_run_document_id'), 'extracted_fields', ['run_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_run_document_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_schema_fields_document_id'), table_name='schema_fields')
    op.drop_table('schema_fields')
    op.drop_index(op.f('ix_run_documents_run_id'), table_name='run_documents')
    op.drop_table('run_documents')
    op.drop_index(op.f('ix_rule_results_run_id'), table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index(op.f('ix_workflow_rules_workflow_id'), table_name='workflow_rules')
    op.drop_table('workflow_rules')
    op.drop_index(op.f('ix_runs_workflow_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_documents_workflow_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('workflows')
    op.drop_table('rule_templates')
    # ### end Alembic commands ###
