apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repody-local
  namespace: argocd
  annotations:
    repody.dev/summary: Repody platform Helm release (API, web, workers, data, queue)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: repody
  source:
    repoURL: https://github.com/MehdiGououiad/repody.git
    targetRevision: master
    path: deploy/helm/repody
    helm:
      releaseName: repody
      valueFiles:
        - values.yaml
        - values-local.yaml
        - values-local-images.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: repody
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 5
