apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: repody
  namespace: argocd
spec:
  description: Repody workloads
  sourceRepos:
    - https://github.com/MehdiGououiad/repody.git
  destinations:
    - namespace: repody
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: gateway.networking.k8s.io
      kind: GatewayClass
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: Job
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: gateway.networking.k8s.io
      kind: Gateway
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.envoyproxy.io
      kind: EnvoyProxy
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
