apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repody-postgres-app
  namespace: repody-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-repody
    kind: ClusterSecretStore
  target:
    name: repody-postgres-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: repody/production/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: repody/production/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repody-postgres-backup
  namespace: repody-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-repody
    kind: ClusterSecretStore
  target:
    name: repody-postgres-backup
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: repody/production/postgres-backup
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: repody/production/postgres-backup
        property: SECRET_ACCESS_KEY
