apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-repody
spec:
  provider:
    vault:
      server: https://vault.yourdomain.com
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: repody
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
