{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "audit-platform.fullname" . }}-ingress
  labels:
    {{- include "audit-platform.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
        {{- if .Values.ingress.filesHost }}
        - {{ .Values.ingress.filesHost }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "audit-platform.fullname" . }}-web
                port:
                  number: 3000
    {{- if .Values.ingress.filesHost }}
    - host: {{ .Values.ingress.filesHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9000
    {{- end }}
{{- end }}
